name: Maven build
description: Maven build

inputs:
  central-token:
    description: Maven central token
    required: false
    default: ''
  central-user:
    description: Maven central user
    required: false
    default: ''
  coveralls-token:
    description: Coveralls repo token
    required: false
    default: ''
  maven-goal:
    description: Maven goal(s)
    required: true
  maven-version:
    description: Maven version
    required: false
    default: 3.9.9
  gpg-passphrase:
    description: GPG passphrase
    required: false
    default: ''
  gpg-private-key:
    description: GPG private key
    required: false
    default: ''
  ssh-private-key:
    description: SSH private key
    required: false
    default: ''

runs:
  using: composite
  steps:
    - if: github.workflow == 'maven-release'
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}

    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
        cache: maven
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        gpg-private-key: ${{ inputs.gpg-private-key }}
        server-id: central
        server-username: MAVEN_USERNAME
        server-password: MAVEN_CENTRAL_TOKEN

    - uses: stCarolas/setup-maven@v5
      with:
        maven-version: ${{ inputs.maven-version }}

    - run: mvn -V -B help:active-profiles ${{ inputs.maven-goal }}
      shell: bash
      env:
        MAVEN_OPTS: -Xms1024m -Xmx2024m -XX:+TieredCompilation -XX:TieredStopAtLevel=1
        COVERALLS_REPO_TOKEN: ${{ inputs.coveralls-token }}
        MAVEN_USERNAME: ${{ inputs.central_user }}
        MAVEN_CENTRAL_TOKEN: ${{ inputs.central_token }}
        MAVEN_GPG_PASSPHRASE: ${{ inputs.MAVEN_GPG_PASSPHRASE }}
