name: go-test

on:
  workflow_call:
    inputs:
      enable-coveralls:
        default: true
        description: Enable Coveralls
        required: false
        type: boolean

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - run: go build -v ./...
      - name: Run linters
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
      - run: go test -v -coverprofile=coverage.out -timeout=120s ./...
      - if: inputs.enable-coveralls
        name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: coverage.out
        env:
          COVERALLS_API_TOKEN: ${{ secrets.COVERALLS_API_TOKEN }}
