name: maven-release

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: dangernoodle-io/.github/.github/actions/checkout@main

      - name: Build
        uses: dangernoodle-io/.github/.github/actions/maven@main
        with:
          maven-goal: release:prepare release:perform
          central-user: ${{ secrets.BUILD_BOT_CENTRAL_USER }}
          central-token: ${{ secrets.BUILD_BOT_CENTRAL_TOKEN }}
          coveralls-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          gpg-passphrase: ${{ secrets.BUILD_BOT_GPG_PASSPHRASE }}
          ssh-private-key: ${{ secrets.BUILD_BOT_SSH_PRIVATE_KEY }}
