name: terraform-provider-test

on:
  workflow_call:
    inputs:
      enable-coveralls:
        default: true
        description: Enable Coveralls
        required: false
        type: boolean

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - run: go build -v .
      - name: Run linters
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_wrapper: false
      - run: make generate
        env:
          GOTOOLCHAIN: auto
      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'make generate' command and commit."; exit 1)

  test:
    name: Terraform Provider Acceptance Tests
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - '1.8.*'
          - '1.9.*'
          - '1.10.*'
          - '1.11.*'
          - '1.12.*'
          - '1.13.*'
          - '1.14.*'
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false
      - run: go mod download
      - env:
          TF_ACC: "1"
        run: go test -v -coverprofile=coverage.out ./internal/provider/
        timeout-minutes: 10
      - if: inputs.enable-coveralls && matrix.terraform == '1.14.*'
        name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: coverage.out

  summary:
    name: Terraform Provider Tests
    needs: [build, generate, test]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
